nelmio_api_doc:
    documentation:
        info:
            title: API Documentation
            description: Your API description
            version: 1.0.0
    areas:
        path_patterns: 
            - ^/api(?!/doc) 
